import meta from './meta.json';
import { isWhitespaceOnly, parseWellFormed, type XmlNode } from './parse';

export { meta };

export { XmlFormatterError } from './errors';
export * from './c14n';
export * from './tree';

export type FormatMode = 'format' | 'minify' | 'check';

export interface FormatXmlOptions {
  mode?: FormatMode;
  /** Spaces per indent level, used by 'format'. Default 2. */
  indent?: number;
  /** Remove comments, used by 'minify'. Default false. */
  removeComments?: boolean;
}

export interface FormatXmlResult {
  output: string;
  /** Count of XML elements read. */
  elements: number;
  /** Count of XML attributes read, across every element. */
  attributes: number;
  /** Deepest element nesting level found (the root element is level 1). */
  maxDepth: number;
}

/** True when every child is a comment, processing instruction, CDATA section or element, with any text child whitespace-only. */
function isElementOnlyContent(children: XmlNode[]): boolean {
  for (const child of children) {
    if (child.type === 'text' && !isWhitespaceOnly(child.text)) return false;
  }
  return true;
}

function indentOf(depth: number, size: number): string {
  return ' '.repeat(depth * size);
}

function renderFormattedNode(
  node: XmlNode,
  depth: number,
  inheritedSpace: 'default' | 'preserve',
  source: string,
  indentSize: number,
  out: string[],
): void {
  if (node.type === 'text') return; // top-level whitespace-only text is dropped, regenerated by the parent
  if (node.type !== 'element') {
    out.push(indentOf(depth, indentSize) + node.raw);
    return;
  }
  const effectiveSpace = node.xmlSpace ?? inheritedSpace;
  if (node.selfClosing || node.children.length === 0) {
    out.push(indentOf(depth, indentSize) + node.startRaw + (node.endRaw ?? ''));
    return;
  }
  if (effectiveSpace === 'preserve' || !isElementOnlyContent(node.children)) {
    out.push(indentOf(depth, indentSize) + source.slice(node.start, node.end));
    return;
  }
  out.push(indentOf(depth, indentSize) + node.startRaw);
  for (const child of node.children) renderFormattedNode(child, depth + 1, effectiveSpace, source, indentSize, out);
  out.push(indentOf(depth, indentSize) + (node.endRaw ?? ''));
}

function renderFormatted(roots: XmlNode[], source: string, indentSize: number): string {
  const out: string[] = [];
  for (const root of roots) renderFormattedNode(root, 0, 'default', source, indentSize, out);
  return out.join('\n');
}

function renderMinifiedNode(
  node: XmlNode,
  inheritedSpace: 'default' | 'preserve',
  source: string,
  removeComments: boolean,
  out: string[],
): void {
  if (node.type === 'text') return;
  if (node.type === 'comment') {
    if (!removeComments) out.push(node.raw);
    return;
  }
  if (node.type !== 'element') {
    out.push(node.raw);
    return;
  }
  const effectiveSpace = node.xmlSpace ?? inheritedSpace;
  if (node.selfClosing || node.children.length === 0) {
    out.push(node.startRaw + (node.endRaw ?? ''));
    return;
  }
  if (effectiveSpace === 'preserve' || !isElementOnlyContent(node.children)) {
    out.push(source.slice(node.start, node.end));
    return;
  }
  out.push(node.startRaw);
  for (const child of node.children) renderMinifiedNode(child, effectiveSpace, source, removeComments, out);
  out.push(node.endRaw ?? '');
}

function renderMinified(roots: XmlNode[], source: string, removeComments: boolean): string {
  const out: string[] = [];
  for (const root of roots) renderMinifiedNode(root, 'default', source, removeComments, out);
  return out.join('');
}

/**
 * Checks XML 1.0 well-formedness, formats with indentation or minifies,
 * changing only whitespace between markup -- text, attributes, tags and
 * CDATA are never rewritten. Any document with a DOCTYPE is refused before
 * parsing (XML 1.0 section 2.8), and any entity reference other than the
 * five predefined entities or a numeric character reference is refused
 * (Well-formedness constraint: Entity Declared, section 4.1), since no
 * DOCTYPE is ever read to declare one.
 */
export function formatXml(source: string, options: FormatXmlOptions = {}): FormatXmlResult {
  const { mode = 'format', indent = 2, removeComments = false } = options;
  const indentSize = Math.max(0, indent);

  const { roots, elements, attributes, maxDepth } = parseWellFormed(source);

  let output: string;
  if (mode === 'check') {
    output = source;
  } else if (mode === 'minify') {
    output = renderMinified(roots, source, removeComments);
  } else {
    output = renderFormatted(roots, source, indentSize);
  }

  return { output, elements, attributes, maxDepth };
}
