/**
 * Published shfmt fixtures, vendored verbatim.
 *
 * Repository: https://github.com/mvdan/sh
 * Tag:        v3.13.1
 * Path:       cmd/shfmt/testdata/script/flags.txtar
 * URL:        https://github.com/mvdan/sh/blob/v3.13.1/cmd/shfmt/testdata/script/flags.txtar
 * Licence:    BSD-3-Clause (see ./LICENSE, the repository LICENSE at the same tag, unmodified)
 * Fetched:    2026-10-01 with curl from raw.githubusercontent.com
 *
 * Each constant is one section of the txtar file, between its "-- name --" line and the next one, generated by a
 * throwaway script with JSON.stringify, never typed by hand, so every tab and trailing space survives. Do not edit.
 */

/** Section "flags-input" of cmd/shfmt/testdata/script/flags.txtar at v3.13.1 (the input every flags golden is produced from) */
export const FLAGS_INPUT = "foo() {\n\tbar &&\n\t\tbaz\n\n\tcase $i in\n\tj)\n\t\tz\n\t\t;;\n\tesac\n\n\tspace >redirs\n\n\tkeep    padding\n}\n";

/** Section "flags-output.indent-golden" of cmd/shfmt/testdata/script/flags.txtar at v3.13.1 (produced with shfmt -i 2) */
export const FLAGS_INDENT_GOLDEN = "foo() {\n  bar &&\n    baz\n\n  case $i in\n  j)\n    z\n    ;;\n  esac\n\n  space >redirs\n\n  keep padding\n}\n";

/** Section "flags-output.keep-padding-golden" of cmd/shfmt/testdata/script/flags.txtar at v3.13.1 (produced with shfmt -kp; apart from the one padding line it is the default output) */
export const FLAGS_KEEP_PADDING_GOLDEN = "foo() {\n\tbar &&\n\t\tbaz\n\n\tcase $i in\n\tj)\n\t\tz\n\t\t;;\n\tesac\n\n\tspace >redirs\n\n\tkeep  padding\n}\n";

/** Section "input-mksh" of cmd/shfmt/testdata/script/flags.txtar at v3.13.1 (valid only as mksh; shfmt -ln=mksh prints it, the default (bash) refuses it) */
export const INPUT_MKSH = "coprocess |&\n";

/** Section "input-mksh-shebang" of cmd/shfmt/testdata/script/flags.txtar at v3.13.1 (the same coprocess with a first line naming mksh) */
export const INPUT_MKSH_SHEBANG = "#!/bin/mksh\ncoprocess |&\n";

/** Section "input-bash-arrays" of cmd/shfmt/testdata/script/flags.txtar at v3.13.1 (upstream refuses this in POSIX mode with "parsed as posix via -ln=auto") */
export const INPUT_BASH_ARRAYS = "#!/bin/sh\nfoo=(bar)\n\n";

/** Section "input-bash-extglobs" of cmd/shfmt/testdata/script/flags.txtar at v3.13.1 (upstream refuses this in POSIX mode with "parsed as posix via -ln=auto") */
export const INPUT_BASH_EXTGLOBS = "#!/bin/sh\necho !(a)\n";
