import { it, expect } from 'vitest';
import { parseCreateTableStatements } from '../src/parse';
import { tokenize, SqlSyntaxError } from '../src/tokenize';

// PostgreSQL: https://www.postgresql.org/docs/current/sql-createtable.html
// (quoted): "CREATE [ ... ] TABLE [ IF NOT EXISTS ] table_name ( ... )"
// MySQL: https://dev.mysql.com/doc/refman/8.4/en/create-table.html (quoted):
// "column_definition : data_type [NOT NULL | NULL] [DEFAULT { literal | (
// expr )} ] ... [AUTO_INCREMENT] ... [[PRIMARY] KEY]"
// SQLite: https://www.sqlite.org/lang_createtable.html (quoted, from the
// railroad-diagram text): column-constraint includes "PRIMARY KEY ...
// AUTOINCREMENT"
// SQL Server: .../create-table-transact-sql (quoted): "[ IDENTITY [ (
// seed , increment ) ] ]" as a column_definition option

it('PostgreSQL IF NOT EXISTS and a serial primary key are both read', () => {
  const result = parseCreateTableStatements(
    'CREATE TABLE IF NOT EXISTS widgets (id serial PRIMARY KEY, name text NOT NULL);',
  );
  expect(result.tables).toHaveLength(1);
  const id = result.tables[0]!.columns[0]!;
  expect(id.typeKind).toBe('int');
  expect(id.autoIncrement).toBe(true);
  expect(id.primaryKey).toBe(true);
});

it('multi-word types are read as one type: double precision, character varying, timestamp with time zone', () => {
  const result = parseCreateTableStatements(
    'CREATE TABLE t (a double precision, b character varying(20), c timestamp with time zone, d timestamp without time zone);',
  );
  const [a, b, c, d] = result.tables[0]!.columns;
  expect(a!.typeKind).toBe('float');
  expect(a!.rawType).toBe('double precision');
  expect(b!.typeKind).toBe('string');
  expect(b!.rawType).toBe('character varying(20)');
  expect(c!.typeKind).toBe('datetime');
  expect(c!.rawType).toBe('timestamp with time zone');
  expect(d!.typeKind).toBe('datetime');
});

it('MySQL unsigned integer modifiers do not change the inferred kind', () => {
  const result = parseCreateTableStatements('CREATE TABLE t (a int unsigned, b bigint unsigned zerofill);');
  expect(result.tables[0]!.columns[0]!.typeKind).toBe('int');
  expect(result.tables[0]!.columns[1]!.typeKind).toBe('bigint');
});

it('GENERATED ALWAYS AS IDENTITY and GENERATED BY DEFAULT AS IDENTITY are auto-increment markers', () => {
  const always = parseCreateTableStatements('CREATE TABLE t (id integer GENERATED ALWAYS AS IDENTITY, name text);');
  expect(always.tables[0]!.columns[0]!.autoIncrement).toBe(true);

  const byDefault = parseCreateTableStatements(
    'CREATE TABLE t (id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1), name text);',
  );
  expect(byDefault.tables[0]!.columns[0]!.autoIncrement).toBe(true);
});

it('a GENERATED ALWAYS AS (expr) computed column is reported, not guessed', () => {
  const result = parseCreateTableStatements(
    'CREATE TABLE t (id integer, full_name text GENERATED ALWAYS AS (id) STORED);',
  );
  expect(result.notConverted.some((n) => n.reason === 'GENERATED computed column')).toBe(true);
});

it('an unknown column type is reported and does not appear as a converted column', () => {
  const result = parseCreateTableStatements('CREATE TABLE t (id integer, loc geometry);');
  expect(result.tables[0]!.columns.map((c) => c.name)).toEqual(['id']);
  expect(result.notConverted.some((n) => n.text.includes('loc') && n.text.includes('geometry'))).toBe(true);
});

it('tokenize skips line and block comments', () => {
  const tokens = tokenize('CREATE -- a comment\n TABLE /* block\ncomment */ t (id integer);');
  const words = tokens.filter((t) => t.type === 'ident').map((t) => t.text);
  expect(words).toEqual(['CREATE', 'TABLE', 't', 'id', 'integer']);
});

it('an unterminated block comment is refused with its position', () => {
  expect(() => tokenize('CREATE TABLE t (id integer); /* never closed')).toThrow(SqlSyntaxError);
});
