/**
 * Published dart_style fixtures, vendored verbatim.
 *
 * Repository: https://github.com/dart-lang/dart_style
 * Tag:        v3.1.4 (the dart_style version the engine's own source map names)
 * Files:      test/tall/top_level/import.unit and test/tall/regression/0000/0084.unit
 * URL:        https://github.com/dart-lang/dart_style/tree/v3.1.4/test/tall
 * Licence:    BSD-3-Clause (see ./LICENSE, the repository LICENSE at the same tag, unmodified)
 * Fetched:    2026-10-01 with curl from raw.githubusercontent.com
 *
 * Each file is read the way lib/src/testing/test_file.dart at the same tag reads it: a first line ending in a bar
 * gives the page width (the position of the bar), `###` comment lines are skipped, each `>>>` line starts a case,
 * each `<<<` line starts its expected output, and every output text keeps the final line break. Each constant is
 * generated by a throwaway script with JSON.stringify, never typed by hand, so every space survives. Do not edit.
 */

/** One case of a dart_style .unit file: the line of its `>>>` marker, its description, the input and the expected output. */
export interface UnitCase {
  line: number;
  description: string;
  input: string;
  expected: string;
}

/** The page width of test/tall/top_level/import.unit at v3.1.4: its first line, `40 columns` followed by spaces and a bar, puts the bar at column 40, which dart_style reads as a page width of 40 */
export const IMPORT_UNIT_WIDTH = 40;

/** Every case of test/tall/top_level/import.unit at v3.1.4 (15 cases) */
export const IMPORT_UNIT_CASES: UnitCase[] = [
  {
    line: 2,
    description: "Discard newlines before first import.",
    input: "\n\nimport 'a.dart';\n",
    expected: "import 'a.dart';\n",
  },
  {
    line: 8,
    description: "Don't split after \"import\" even with long string.",
    input: "import\n'package:some/very/long/import/path.dart';\n",
    expected: "import 'package:some/very/long/import/path.dart';\n",
  },
  {
    line: 13,
    description: "Keep \"as\" on same line.",
    input: "import 'package:foo.dart'\n    as foo;\n",
    expected: "import 'package:foo.dart' as foo;\n",
  },
  {
    line: 18,
    description: "Wrap before \"as\".",
    input: "import 'package:some/path/foo.dart' as foo;\n",
    expected: "import 'package:some/path/foo.dart'\n    as foo;\n",
  },
  {
    line: 23,
    description: "Keep \"deferred as\" on same line.",
    input: "import 'foo.dart'   deferred   as foo;\n",
    expected: "import 'foo.dart' deferred as foo;\n",
  },
  {
    line: 27,
    description: "Wrap before \"deferred\".",
    input: "import 'package:foo/foo.dart' deferred as path;\n",
    expected: "import 'package:foo/foo.dart'\n    deferred as path;\n",
  },
  {
    line: 32,
    description: "Don't split before \"deferred\" and \"as\".",
    input: "import 'package:foo/some/path/foo.dart' deferred as very_long_identifier_path;\n",
    expected: "import 'package:foo/some/path/foo.dart'\n    deferred as very_long_identifier_path;\n",
  },
  {
    line: 37,
    description: "Dotted identifier in configuration.",
    input: "import'a'if(b  . c . d)'e';\n",
    expected: "import 'a' if (b.c.d) 'e';\n",
  },
  {
    line: 41,
    description: "Multiple configurations on one line.",
    input: "import 'a' if (b) 'b' if (c) 'c';\n",
    expected: "import 'a' if (b) 'b' if (c) 'c';\n",
  },
  {
    line: 45,
    description: "If configurations don't fit, they all split.",
    input: "import 'long/import/url.dart' if (b) 'b' if (c) 'c';\n",
    expected: "import 'long/import/url.dart'\n    if (b) 'b'\n    if (c) 'c';\n",
  },
  {
    line: 51,
    description: "Configurations don't split before URI.",
    input: "import 'long/import/url.dart' if (config) 'very/long/configured/import/url.dart';\n",
    expected: "import 'long/import/url.dart'\n    if (config) 'very/long/configured/import/url.dart';\n",
  },
  {
    line: 56,
    description: "Unsplit configuration with `==`.",
    input: "import 'a.dart' if (b == 's') 'c';\n",
    expected: "import 'a.dart' if (b == 's') 'c';\n",
  },
  {
    line: 60,
    description: "Split before `if` before `==`.",
    input: "import 'some/uri.dart' if (debug == 'string') 'c';\n",
    expected: "import 'some/uri.dart'\n    if (debug == 'string') 'c';\n",
  },
  {
    line: 65,
    description: "Split before `==` in configuration.",
    input: "import 'some/uri.dart' if (config.name.debug == 'string') 'c';\n",
    expected: "import 'some/uri.dart'\n    if (config.name.debug ==\n        'string') 'c';\n",
  },
  {
    line: 71,
    description: "Both configuration and prefix.",
    input: "import 'foo.dart' if (config == 'value') 'other.dart' as foo;\n",
    expected: "import 'foo.dart'\n    if (config == 'value') 'other.dart'\n    as foo;\n",
  },
];

/** The page width of test/tall/regression/0000/0084.unit at v3.1.4: the file has no width line, so dart_style runs its cases at its default page width of 80 */
export const DEFAULT_WIDTH_UNIT_WIDTH = 80;

/** Every case of test/tall/regression/0000/0084.unit at v3.1.4 (4 cases) */
export const DEFAULT_WIDTH_UNIT_CASES: UnitCase[] = [
  {
    line: 1,
    description: "",
    input: "Future<TextureAtlas> load(String url, BitmapDataLoadOptions bitmapDataLoadOptions) {\n  HttpRequest.getString(url).then((textureAtlasJson) {\n    ;\n\n    loader.then(() {\n      ;\n    }).catchError(() {\n      ;\n    });\n  });\n}\n",
    expected: "Future<TextureAtlas> load(\n  String url,\n  BitmapDataLoadOptions bitmapDataLoadOptions,\n) {\n  HttpRequest.getString(url).then((textureAtlasJson) {\n    ;\n\n    loader\n        .then(() {\n          ;\n        })\n        .catchError(() {\n          ;\n        });\n  });\n}\n",
  },
  {
    line: 30,
    description: "",
    input: "class SoundSprite {\n  static Future<SoundSprite> load(String url, [SoundLoadOptions soundLoadOptions = null]) {\n    HttpRequest.getString(url).then((soundSpriteJson) {\n      if (segments is Map) {\n      }\n\n      Sound.load(soundUrl, soundLoadOptions).then((Sound sound) {\n        ;\n      }).catchError((error) {\n        ;\n      });\n\n    });\n  }\n}\n",
    expected: "class SoundSprite {\n  static Future<SoundSprite> load(\n    String url, [\n    SoundLoadOptions soundLoadOptions = null,\n  ]) {\n    HttpRequest.getString(url).then((soundSpriteJson) {\n      if (segments is Map) {}\n\n      Sound.load(soundUrl, soundLoadOptions)\n          .then((Sound sound) {\n            ;\n          })\n          .catchError((error) {\n            ;\n          });\n    });\n  }\n}\n",
  },
  {
    line: 65,
    description: "don't split method multisplits too early because of pending line after \";\"",
    input: "main() {\n  ;\n  receiver.a(() {\n    ;\n  }).b(() {\n    ;\n  });\n}\n",
    expected: "main() {\n  ;\n  receiver\n      .a(() {\n        ;\n      })\n      .b(() {\n        ;\n      });\n}\n",
  },
  {
    line: 85,
    description: "don't nest too early because of comment before method chain",
    input: "main() {\n  //\n  receiver.a(() {\n    ;\n  }).b(() {\n    ;\n  });\n}\n",
    expected: "main() {\n  //\n  receiver\n      .a(() {\n        ;\n      })\n      .b(() {\n        ;\n      });\n}\n",
  },
];
