/**
 * Small, original word lists written for this package (not copied from any
 * other folder). Every list is picked from with the seeded generator in
 * `index.ts`, never with the platform's own random-number function.
 */

/** About 40 given names. */
export const FIRST_NAMES = [
  'Ada',
  'Alan',
  'Grace',
  'Linus',
  'Margaret',
  'Katherine',
  'John',
  'Barbara',
  'Edsger',
  'Hedy',
  'Radia',
  'Vint',
  'Tim',
  'Donald',
  'Frances',
  'Claude',
  'Dennis',
  'Ken',
  'Brian',
  'Bjarne',
  'James',
  'Guido',
  'Yukihiro',
  'Anders',
  'Rasmus',
  'Larry',
  'Rich',
  'Rob',
  'Ryan',
  'Evan',
  'Douglas',
  'Ivan',
  'Martin',
  'Niklaus',
  'Dana',
  'Shafi',
  'Whitfield',
  'Adi',
  'Ron',
  'Leonard',
];

/** About 40 family names. */
export const LAST_NAMES = [
  'Lovelace',
  'Turing',
  'Hopper',
  'Torvalds',
  'Hamilton',
  'Johnson',
  'Backus',
  'Liskov',
  'Dijkstra',
  'Lamarr',
  'Perlman',
  'Cerf',
  'Berners-Lee',
  'Knuth',
  'Allen',
  'Shannon',
  'Ritchie',
  'Thompson',
  'Kernighan',
  'Stroustrup',
  'Gosling',
  'Van Rossum',
  'Matsumoto',
  'Hejlsberg',
  'Lerdorf',
  'Wall',
  'Hickey',
  'Pike',
  'Dahl',
  'Goldberg',
  'Crockford',
  'Sutherland',
  'Fowler',
  'Wirth',
  'Ullman',
  'Goldwasser',
  'Diffie',
  'Shamir',
  'Rivest',
  'Adleman',
];

/** About 40 city names, mixing real and clearly fictional so no result implies a real person's actual address. */
export const CITIES = [
  'Rivergate',
  'Northfield',
  'Fairhaven',
  'Elmwood',
  'Brookline',
  'Castleton',
  'Millbrook',
  'Oakdale',
  'Westbury',
  'Sunnyvale',
  'Lakeview',
  'Ashford',
  'Bridgeport',
  'Clearwater',
  'Dunmore',
  'Eastgate',
  'Fernwood',
  'Glenmoor',
  'Harborview',
  'Ironwood',
  'Juniper Bay',
  'Kingsford',
  'Ledgemont',
  'Maplewood',
  'Northgate',
  'Overton',
  'Pinehurst',
  'Queensbridge',
  'Ridgeway',
  'Silverton',
  'Thornbury',
  'Union Hill',
  'Vantage',
  'Westfield',
  'Xenford',
  'Yorkgate',
  'Zionsville',
  'Ashgrove',
  'Briarcliff',
  'Cedar Falls',
];

/** About 40 street names. */
export const STREET_NAMES = [
  'Maple',
  'Oak',
  'Elm',
  'Cedar',
  'Birch',
  'Pine',
  'Willow',
  'Chestnut',
  'Walnut',
  'Spruce',
  'Aspen',
  'Magnolia',
  'Sycamore',
  'Poplar',
  'Alder',
  'Hazel',
  'Juniper',
  'Larch',
  'Rowan',
  'Beech',
  'Meadow',
  'Sunset',
  'Harbor',
  'Ridge',
  'Highland',
  'Lakeside',
  'Hillcrest',
  'Fairview',
  'Riverside',
  'Springfield',
  'Northgate',
  'Westgate',
  'Kingston',
  'Franklin',
  'Jefferson',
  'Lincoln',
  'Adams',
  'Monroe',
  'Wilson',
  'Grant',
];

export const STREET_SUFFIXES = [
  'Street',
  'Avenue',
  'Road',
  'Lane',
  'Drive',
  'Court',
  'Boulevard',
  'Way',
  'Place',
  'Terrace',
];

/** About 40 short, generic words used for `word`, `sentence`, `username` and `company`. */
export const WORDS = [
  'amber',
  'brisk',
  'cobalt',
  'drift',
  'ember',
  'falcon',
  'granite',
  'harbor',
  'ivory',
  'jasper',
  'kestrel',
  'lantern',
  'marble',
  'nimbus',
  'orchard',
  'pebble',
  'quartz',
  'ripple',
  'summit',
  'thistle',
  'umbra',
  'vellum',
  'willow',
  'xenon',
  'yonder',
  'zephyr',
  'anchor',
  'beacon',
  'canyon',
  'delta',
  'echo',
  'forge',
  'glimmer',
  'horizon',
  'iris',
  'juniper',
  'knoll',
  'lumen',
  'meadow',
  'novo',
];

/** About 40 nouns used to close out a generated company name. */
export const COMPANY_SUFFIXES = [
  'Group',
  'Partners',
  'Holdings',
  'Studio',
  'Labs',
  'Works',
  'Collective',
  'Ventures',
  'Systems',
  'Solutions',
  'Industries',
  'Associates',
  'Consulting',
  'Enterprises',
  'Networks',
  'Dynamics',
  'Technologies',
  'Foundry',
  'Cooperative',
  'Alliance',
];

/**
 * RFC 2606 reserved domains, so a generated email or URL never points at a
 * real host.
 */
export const EXAMPLE_DOMAINS = ['example.com', 'example.net', 'example.org'];
