"""Builds the test fonts of the Font Inspector with fontTools (authoring time only; nothing here ships).

Every font is generated by this script, so no third-party font licence is involved: each carries a statement in name ID
13 that it is released as CC0-1.0. All dates are fixed, so a rebuild is byte for byte the same file.

Usage:  python build-fonts.py <output folder> [canary text]

Writes det-sans.ttf (the small font of the live fixture), det-sans-canary.ttf (the same with the page's canary appended to
name ID 13), plain.ttf, mac-names.ttf, preview.ttf, variable.ttf, cff.otf and collection.ttc, and fontTools' own WOFF and
WOFF2 files of plain.ttf (plain.woff, plain.woff2 and with-blocks.woff2, which also carries a metadata block and a private data
block). It prints a JSON list of every file's size and sha256 value. The WOFF and WOFF2 files are read for their tables only;
they are never compared byte for byte.
"""
import hashlib
import io
import json
import os
import sys

from fontTools.feaLib.builder import addOpenTypeFeaturesFromString
from fontTools.fontBuilder import FontBuilder
from fontTools.misc.timeTools import timestampFromString
from fontTools.pens.t2CharStringPen import T2CharStringPen
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.ttLib import TTCollection, TTFont
from fontTools.ttLib.sfnt import WOFFFlavorData
from fontTools.ttLib.tables._c_m_a_p import cmap_format_14

STAMP = timestampFromString('Thu Jan  1 00:00:00 2026')
CC0 = 'Test font built for this project, released as CC0-1.0.'
CC0_URL = 'https://creativecommons.org/publicdomain/zero/1.0/'
CANARY_DEFAULT = 'CANARY-7f3a91-font-inspector-d4e8b2'

CHARS = {
    0x20: 'space', 0x41: 'A', 0x42: 'B', 0x43: 'C', 0xE9: 'eacute', 0x1F600: 'u1F600', 0x4E2D: 'uni4E2D',
    0x66: 'f', 0x69: 'i', 0xFB01: 'fi',
}
ORDER = ['.notdef', 'space', 'A', 'B', 'C', 'eacute', 'u1F600', 'uni4E2D', 'f', 'i', 'fi', 'Aacute_composite']


def rect(pen, x0, y0, x1, y1):
    pen.moveTo((x0, y0))
    pen.lineTo((x0, y1))
    pen.lineTo((x1, y1))
    pen.lineTo((x1, y0))
    pen.closePath()


def curve(pen, cx, cy, r):
    # four quadratic segments with off-curve and on-curve points
    pen.moveTo((cx - r, cy))
    pen.qCurveTo((cx - r, cy + r), (cx, cy + r))
    pen.qCurveTo((cx + r, cy + r), (cx + r, cy))
    pen.qCurveTo((cx + r, cy - r), (cx, cy - r))
    pen.qCurveTo((cx - r, cy - r), (cx - r, cy))
    pen.closePath()


def names_for(family, style='Regular', mac=False, description=CC0):
    names = {
        'familyName': family,
        'styleName': style,
        'uniqueFontIdentifier': f'{family}-{style}-test',
        'fullName': f'{family} {style}',
        'psName': f'{family.replace(" ", "")}-{style}',
        'version': 'Version 1.000',
        'licenseDescription': description,
        'licenseInfoURL': CC0_URL,
        'copyright': 'No rights reserved.',
        'designer': 'Test builder',
        'description': 'A tiny font for tests',
    }
    return names


def lsb_from_bounds(fb, shift=0):
    """Left side bearings equal to each glyph's xMin (minus `shift`), as every real font has them."""
    glyf = fb.font['glyf']
    metrics = {}
    for i, name in enumerate(ORDER):
        glyph = glyf[name]
        glyph.recalcBounds(glyf)
        xmin = glyph.xMin if glyph.numberOfContours != 0 else 0
        advance = 300 if name == 'space' else 500 + 20 * (i % 7)
        metrics[name] = (advance, xmin - (shift if glyph.numberOfContours > 0 else 0))
    return metrics


def build_ttf(family, mac=False, features=True, fstype=0, extra_cmap=False, composite=True, shift=0, revision=None,
              unicode_names=False, variable=False):
    fb = FontBuilder(1000, isTTF=True)
    update = {'created': STAMP, 'modified': STAMP}
    if revision is not None:
        update['fontRevision'] = revision
    fb.updateHead(**update)
    fb.setupGlyphOrder(ORDER)
    cmap = dict(CHARS)
    cmap[0xC1] = 'Aacute_composite'
    fb.setupCharacterMap(cmap)
    glyphs = {}
    for name in ORDER:
        pen = TTGlyphPen(glyphs)
        if name == '.notdef':
            rect(pen, 50, 0, 450, 700)
        elif name == 'space':
            pass
        elif name == 'A':
            rect(pen, 100, 0, 500, 700)
        elif name == 'B':
            rect(pen, 100, 0, 300, 700)
            rect(pen, 350, 0, 550, 400)
        elif name == 'C':
            curve(pen, 300, 350, 300)
        elif name == 'eacute':
            rect(pen, 100, 0, 400, 500)
            rect(pen, 200, 520, 300, 600)
        elif name == 'u1F600':
            curve(pen, 400, 350, 350)
        elif name == 'uni4E2D':
            rect(pen, 100, 100, 900, 200)
            rect(pen, 450, 0, 550, 800)
        elif name == 'f':
            rect(pen, 150, 0, 250, 700)
        elif name == 'i':
            rect(pen, 150, 0, 250, 500)
        elif name == 'fi':
            rect(pen, 150, 0, 250, 700)
            rect(pen, 350, 0, 450, 500)
        elif name == 'Aacute_composite':
            if composite:
                pen.addComponent('A', (1, 0, 0, 1, 0, 0))
                pen.addComponent('eacute', (1, 0, 0, 1, 300, 600))
            else:
                rect(pen, 100, 0, 500, 700)
        glyphs[name] = pen.glyph()
    fb.setupGlyf(glyphs)
    fb.setupHorizontalMetrics(lsb_from_bounds(fb, shift))
    fb.setupHorizontalHeader(ascent=800, descent=-200, lineGap=90)
    fb.setupNameTable(names_for(family), mac=mac)
    if unicode_names:
        # Unicode platform (0) and Windows UCS-4 (3, 10) records beside the Windows (3, 1) ones.
        name = fb.font['name']
        name.setName(family, 1, 0, 3, 0)
        name.setName(f'{family} Regular', 4, 0, 3, 0)
        name.setName(f'{family} UCS-4', 4, 3, 10, 0x409)
    fb.setupOS2(sTypoAscender=780, sTypoDescender=-220, sTypoLineGap=100, usWinAscent=900, usWinDescent=250,
                fsType=fstype, sxHeight=500, sCapHeight=700, achVendID='TEST', usWeightClass=400, usWidthClass=5)
    fb.setupPost()
    if features:
        addOpenTypeFeaturesFromString(fb.font, '''
languagesystem DFLT dflt;
languagesystem latn dflt;
languagesystem latn TRK;
feature liga { sub f i by fi; } liga;
feature kern { pos A B -50; } kern;
feature smcp { sub A by B; } smcp;
feature ss01 { sub C by B; } ss01;
''')
    if extra_cmap:
        # a variation selector subtable (format 14); the supplementary character already gives a format 12 subtable
        sub14 = cmap_format_14(14)
        sub14.platformID, sub14.platEncID, sub14.language = 0, 5, 0
        sub14.cmap = {}
        sub14.uvsDict = {0xFE0F: [(0x41, None), (0xE9, 'B')]}
        fb.font['cmap'].tables.append(sub14)
    if variable:
        fb.setupFvar([('wght', 100, 400, 900, 'Weight')], [{'location': {'wght': 700}, 'stylename': 'Bold'}])
    return fb.font


def build_cff():
    fb = FontBuilder(1000, isTTF=False)
    fb.updateHead(created=STAMP, modified=STAMP)
    order = ['.notdef', 'space', 'A', 'B', 'C']
    fb.setupGlyphOrder(order)
    fb.setupCharacterMap({0x41: 'A', 0x42: 'B', 0x43: 'C', 0x20: 'space'})
    charstrings = {}
    for name in order:
        pen = T2CharStringPen(600, None)
        if name == '.notdef':
            rect(pen, 50, 0, 450, 700)
        elif name == 'A':
            rect(pen, 100, 0, 500, 700)
        elif name == 'B':
            pen.moveTo((100, 0))
            pen.curveTo((100, 200), (300, 400), (300, 600))
            pen.lineTo((500, 600))
            pen.lineTo((500, 0))
            pen.closePath()
        elif name == 'C':
            pen.moveTo((100, 0))
            pen.lineTo((300, 700))
            pen.lineTo((500, 0))
            pen.closePath()
        charstrings[name] = pen.getCharString()
    fb.setupCFF('ScratchCFF-Regular', {'FullName': 'Scratch CFF Regular', 'FamilyName': 'Scratch CFF'}, charstrings, {})
    fb.setupHorizontalMetrics({n: (600, 0) for n in order})
    fb.setupHorizontalHeader(ascent=800, descent=-200)
    fb.setupNameTable(names_for('Scratch CFF'))
    fb.setupOS2(sTypoAscender=800, sTypoDescender=-200, usWinAscent=800, usWinDescent=200)
    fb.setupPost()
    return fb.font


def build_det_sans(canary=None):
    """The 1,672 byte font of the live fixture: seven glyphs, 1000 units per em, liga and kern."""
    fb = FontBuilder(1000, isTTF=True)
    fb.updateHead(created=STAMP, modified=STAMP)
    order = ['.notdef', 'space', 'A', 'B', 'f', 'i', 'f_i']
    fb.setupGlyphOrder(order)
    fb.setupCharacterMap({0x20: 'space', 0x41: 'A', 0x42: 'B', 0x66: 'f', 0x69: 'i'})
    glyphs = {}
    for n in order:
        pen = TTGlyphPen(None)
        if n == '.notdef':
            rect(pen, 100, 0, 500, 700)
        elif n == 'A':
            rect(pen, 100, 0, 500, 700)
        elif n == 'B':
            rect(pen, 100, 0, 300, 700)
            rect(pen, 350, 0, 550, 400)
        elif n == 'f':
            rect(pen, 100, 0, 200, 700)
        elif n == 'i':
            rect(pen, 100, 0, 200, 500)
        elif n == 'f_i':
            rect(pen, 100, 0, 200, 700)
            rect(pen, 300, 0, 400, 500)
        glyphs[n] = pen.glyph()
    fb.setupGlyf(glyphs)
    bounds = {'.notdef': 100, 'space': 0, 'A': 100, 'B': 100, 'f': 100, 'i': 100, 'f_i': 100}
    fb.setupHorizontalMetrics({n: (600, bounds[n]) for n in order})
    fb.setupHorizontalHeader(ascent=800, descent=-200)
    description = CC0 + (' ' + canary if canary else '')
    fb.setupNameTable({
        'familyName': 'Det Sans', 'styleName': 'Regular', 'uniqueFontIdentifier': 'DetSans-Regular-1',
        'fullName': 'Det Sans Regular', 'psName': 'DetSans-Regular', 'version': 'Version 1.000',
        'licenseDescription': description, 'licenseInfoURL': CC0_URL,
    })
    fb.setupOS2(sTypoAscender=800, sTypoDescender=-200, usWinAscent=800, usWinDescent=200, fsType=0, achVendID='TEST',
                sxHeight=500, sCapHeight=700)
    fb.setupPost()
    addOpenTypeFeaturesFromString(
        fb.font,
        'languagesystem DFLT dflt;\nlanguagesystem latn dflt;\n'
        'feature liga { sub f i by f_i; } liga;\nfeature kern { pos A B -40; } kern;\n',
    )
    return fb.font


def flavored(sfnt, flavor, meta=None, priv=None):
    """fontTools' own WOFF or WOFF2 container of an sfnt, optionally with a metadata block and a private data block."""
    font = TTFont(io.BytesIO(sfnt), recalcTimestamp=False)
    font.flavor = flavor
    if meta or priv:
        data = WOFFFlavorData()
        data.majorVersion = 1
        data.minorVersion = 2
        data.metaData = meta
        data.privData = priv
        font.flavorData = data
    return to_bytes(font)


def to_bytes(font):
    buffer = io.BytesIO()
    font.save(buffer)
    return buffer.getvalue()


def build_all(canary):
    files = {}
    files['det-sans.ttf'] = to_bytes(build_det_sans())
    files['det-sans-canary.ttf'] = to_bytes(build_det_sans(canary))
    files['plain.ttf'] = to_bytes(build_ttf('Scratch Sans', extra_cmap=True, revision=1.00390625, unicode_names=True))
    files['mac-names.ttf'] = to_bytes(build_ttf('Café Sans', mac=True, fstype=0x0002, unicode_names=True))
    files['preview.ttf'] = to_bytes(build_ttf('Preview Sans', fstype=0x0004, features=False))
    # The variable font has no composite glyph and left side bearings 50 below each xMin, so the outline shift is tested.
    files['variable.ttf'] = to_bytes(build_ttf('Var Sans', features=False, composite=False, shift=50, variable=True))
    files['cff.otf'] = to_bytes(build_cff())
    first = TTFont(io.BytesIO(files['plain.ttf']), recalcTimestamp=False)
    second = TTFont(io.BytesIO(files['preview.ttf']), recalcTimestamp=False)
    collection = TTCollection()
    collection.fonts = [first, second]
    buffer = io.BytesIO()
    collection.save(buffer)
    files['collection.ttc'] = buffer.getvalue()
    files['plain.woff'] = flavored(files['plain.ttf'], 'woff')
    files['plain.woff2'] = flavored(files['plain.ttf'], 'woff2')
    files['with-blocks.woff2'] = flavored(
        files['plain.ttf'], 'woff2', b'<metadata version="1.0"/>', b'private bytes of the test')
    return files


def main():
    out = sys.argv[1]
    canary = sys.argv[2] if len(sys.argv) > 2 else CANARY_DEFAULT
    os.makedirs(out, exist_ok=True)
    files = build_all(canary)
    listing = []
    for name, data in files.items():
        with open(os.path.join(out, name), 'wb') as handle:
            handle.write(data)
        listing.append({'file': name, 'bytes': len(data), 'sha256': hashlib.sha256(data).hexdigest()})
    print(json.dumps(listing, indent=1))


if __name__ == '__main__':
    main()
