"""Writes src/standard-names.ts: the two standard glyph name lists a font can refer to by number.

Usage:  python make-standard-names.py <path of src/standard-names.ts>

- the 391 standard strings of the Compact Font Format (Adobe Technical Note 5176, Appendix A), which a CFF charset names by
  string identifier below 391;
- the 258 glyph names of the standard Macintosh glyph ordering (Apple TrueType Reference Manual, the post table), which a
  post table of format 1 or 2 refers to by index below 258.

Both lists are fixed by those specifications. They are transcribed here from fontTools 4.64.0 (MIT), which carries the same
lists, so the package does not have to retype 650 names by hand; the unit tests check the counts and spot values against the
specifications. Python is authoring-time only and is never a repository dependency.
"""
import sys

from fontTools.cffLib import cffStandardStrings
from fontTools.ttLib.tables._p_o_s_t import standardGlyphOrder


def array(name, items, doc):
    lines = [f'/** {doc} */', f'export const {name}: readonly string[] = [']
    for item in items:
        lines.append("  '" + item.replace("\\", "\\\\").replace("'", "\\'") + "',")
    lines.append('];')
    return '\n'.join(lines)


def main():
    assert len(cffStandardStrings) == 391, len(cffStandardStrings)
    assert len(standardGlyphOrder) == 258, len(standardGlyphOrder)
    text = '\n'.join([
        '// Generated by test/fixtures/make-standard-names.py. Do not edit by hand: run the script again.',
        '// The lists are fixed by the specifications named at each constant.',
        '',
        array('CFF_STANDARD_STRINGS', cffStandardStrings,
              'The 391 standard strings of the Compact Font Format, by string identifier (Adobe Technical Note 5176, Appendix A).'),
        '',
        array('MAC_GLYPH_NAMES', standardGlyphOrder,
              'The 258 glyph names of the standard Macintosh glyph ordering, by index (Apple TrueType Reference Manual, post table).'),
        '',
    ])
    with open(sys.argv[1], 'w', encoding='utf-8', newline='\n') as handle:
        handle.write(text)
    print('wrote', len(cffStandardStrings), 'and', len(standardGlyphOrder), 'names')


if __name__ == '__main__':
    main()
