// Generates src/blocks.ts from the original Unicode data file Blocks-17.0.0.txt (kept beside this script, unchanged).
//
//   node tools/font-inspector/test/fixtures/unicode/make-blocks.mjs
//
// The test reads this file's `makeBlocksSource` and requires src/blocks.ts to equal its output, so the table can never
// drift from the data file.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

/** The TypeScript source of the block table for the text of a Blocks.txt file. */
export function makeBlocksSource(text, version) {
  const rows = [];
  for (const line of text.split(/\r?\n/)) {
    if (line === '' || line.startsWith('#')) continue;
    const match = /^([0-9A-F]+)\.\.([0-9A-F]+); (.+)$/.exec(line);
    if (!match) throw new Error(`Unexpected line in the blocks file: ${line.slice(0, 40)}`);
    const first = Number.parseInt(match[1], 16);
    const last = Number.parseInt(match[2], 16);
    const hex = (n) => `0x${n.toString(16).padStart(4, "0")}`;
    rows.push(`  [${hex(first)}, ${hex(last)}, ${JSON.stringify(match[3]).replace(/"/g, "'")}],`);
  }
  return [
    `// Generated by test/fixtures/unicode/make-blocks.mjs from Blocks-${version}.txt (Unicode License V3, see`,
    '// unicode-NOTICE.txt). Do not edit by hand: run the script again.',
    '',
    `/** The Unicode version of the block list. */`,
    `export const UNICODE_VERSION = '${version}';`,
    '',
    '/** Every block as [first code point, last code point, name], in code point order. */',
    'export const BLOCKS: readonly (readonly [number, number, string])[] = [',
    ...rows,
    '];',
    '',
  ].join('\n');
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const version = '17.0.0';
  const text = readFileSync(join(here, `Blocks-${version}.txt`), 'utf8');
  writeFileSync(join(here, '..', '..', '..', 'src', 'blocks.ts'), makeBlocksSource(text, version));
  console.log(`Wrote src/blocks.ts from Blocks-${version}.txt`);
}
