/**
 * Test-side generator for `src/binary-data.ts`: reads the permissively
 * licensed binary data this tool bundles directly from the installed
 * pdfjs-dist package's own files, recording bytes and a sha256 alongside
 * the base64 payload. A required test asserts the committed module is
 * exactly what a fresh build from the installed package produces (07-01
 * AN's generator-equality pattern).
 *
 * Only Foxit standard-font data is bundled here (the tracer's own scope);
 * a later task in this same plan extends this generator with the wasm
 * decoders and the ICC profile.
 *
 * Only writes `src/binary-data.ts` back to disk when
 * `process.env.FODT_REGENERATE === '1'`; every other run is read-only.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';

const ROOT = join(__dirname, '..');
const PDFJS_DIR = join(ROOT, 'node_modules', 'pdfjs-dist');
const OUTPUT_PATH = join(ROOT, 'src', 'binary-data.ts');

/** The ten Foxit standard-font files this tool bundles (PDFium BSD-3-Clause), never the four Liberation files (GPL-2.0). */
export const FOXIT_FONT_FILES = [
  'FoxitDingbats.pfb',
  'FoxitFixed.pfb',
  'FoxitFixedBold.pfb',
  'FoxitFixedBoldItalic.pfb',
  'FoxitFixedItalic.pfb',
  'FoxitSerif.pfb',
  'FoxitSerifBold.pfb',
  'FoxitSerifBoldItalic.pfb',
  'FoxitSerifItalic.pfb',
  'FoxitSymbol.pfb',
];

export interface BundledEntry {
  kind: string;
  bytes: number;
  sha256: string;
  base64: string;
}

function readEntry(path: string, kind: string): BundledEntry {
  const bytes = readFileSync(path);
  return {
    kind,
    bytes: bytes.length,
    sha256: createHash('sha256').update(bytes).digest('hex'),
    base64: bytes.toString('base64'),
  };
}

/**
 * Builds the bundled data map from the installed pdfjs-dist package: one
 * entry per Foxit standard-font file, keyed by its own PDF.js file name
 * (the same name `BinaryDataFactory.fetch({ filename })` asks for).
 */
export function buildBinaryData(pdfjsDir: string = PDFJS_DIR): Record<string, BundledEntry> {
  const out: Record<string, BundledEntry> = {};
  for (const filename of FOXIT_FONT_FILES) {
    out[filename] = readEntry(join(pdfjsDir, 'standard_fonts', filename), 'font');
  }
  return out;
}

/** Renders `src/binary-data.ts`'s exact source text from a built data map. */
export function renderBinaryDataModule(entries: Record<string, BundledEntry>): string {
  return [
    '/**',
    ' * Generated by test/build-binary-data.ts from the installed pdfjs-dist',
    ' * package (6.x). Bundles the ten Foxit standard-font files (PDFium',
    " * BSD-3-Clause) this tool answers PDF.js's own BinaryDataFactory",
    ' * requests from -- every byte here is served from memory, never fetched,',
    ' * so rendering a PDF makes no request for font data of any kind. See',
    ' * src/standard-fonts-NOTICE.txt for the full upstream licence text.',
    ' *',
    ' * A wide type annotation on BUNDLED_BINARY_DATA is deliberate: without',
    ' * it, the compiler would infer a literal type from this exact object,',
    ' * and a future regeneration that changes even one byte would then be a',
    ' * type error at every call site, not just a value change.',
    ' */',
    '',
    `export const BUNDLED_BINARY_DATA: Readonly<Record<string, { kind: string; bytes: number; sha256: string; base64: string }>> = ${JSON.stringify(entries, null, 2)} as const;`,
    '',
  ].join('\n');
}

if (process.env.FODT_REGENERATE === '1') {
  writeFileSync(OUTPUT_PATH, renderBinaryDataModule(buildBinaryData()));
}
