/**
 * Published Ruff formatter fixtures, vendored verbatim.
 *
 * Repository: https://github.com/astral-sh/ruff
 * Tag:        0.15.20
 * Paths:      crates/ruff_python_formatter/resources/test/fixtures/ruff/<name>.py (and .options.json)
 *             crates/ruff_python_formatter/tests/snapshots/format@<name>.py.snap
 * URL:        https://github.com/astral-sh/ruff/tree/0.15.20/crates/ruff_python_formatter
 * Licence:    MIT (see ./LICENSE, the repository LICENSE at the same tag, unmodified)
 * Fetched:    2026-10-01 with curl from raw.githubusercontent.com
 *
 * Generated by a throwaway script with JSON.stringify of the fetched bytes, never typed by hand, so
 * every tab, carriage return and trailing space survives. Do not edit.
 */

/** crates/ruff_python_formatter/resources/test/fixtures/ruff/quote_style.py at 0.15.20 */
export const QUOTE_STYLE_INPUT = "'single' # this string is treated as a docstring\n\"double\"\nr'r single'\nr\"r double\"\nf'f single'\nf\"f double\"\nfr'fr single'\nfr\"fr double\"\nrf'rf single'\nrf\"rf double\"\nb'b single'\nb\"b double\"\nrb'rb single'\nrb\"rb double\"\nbr'br single'\nbr\"br double\"\n\n'''single triple'''\n\"\"\"double triple\"\"\"\nr'''r single triple'''\nr\"\"\"r double triple\"\"\"\nf'''f single triple'''\nf\"\"\"f double triple\"\"\"\nfr'''fr single triple'''\nfr\"\"\"fr double triple\"\"\"\nrf'''rf single triple'''\nrf\"\"\"rf double triple\"\"\"\nb'''b single triple'''\nb\"\"\"b double triple\"\"\"\nrb'''rb single triple'''\nrb\"\"\"rb double triple\"\"\"\nbr'''br single triple'''\nbr\"\"\"br double triple\"\"\"\n\n'single1' 'single2'\n'single1' \"double2\"\n\"double1\" 'single2'\n\"double1\" \"double2\"\n\ndef docstring_single_triple():\n    '''single triple'''\n\ndef docstring_double_triple():\n    \"\"\"double triple\"\"\"\n\ndef docstring_double():\n    \"double triple\"\n\ndef docstring_single():\n    'single'\n";

/** Output 1 of crates/ruff_python_formatter/tests/snapshots/format@quote_style.py.snap at 0.15.20 (quote-style = Single, line-width 88, indent-width 4, indent-style space) */
export const QUOTE_STYLE_SINGLE_OUTPUT = "\"single\"  # this string is treated as a docstring\n\n'double'\nr'r single'\nr'r double'\nf'f single'\nf'f double'\nrf'fr single'\nrf'fr double'\nrf'rf single'\nrf'rf double'\nb'b single'\nb'b double'\nrb'rb single'\nrb'rb double'\nrb'br single'\nrb'br double'\n\n\"\"\"single triple\"\"\"\n\"\"\"double triple\"\"\"\nr\"\"\"r single triple\"\"\"\nr\"\"\"r double triple\"\"\"\nf\"\"\"f single triple\"\"\"\nf\"\"\"f double triple\"\"\"\nrf\"\"\"fr single triple\"\"\"\nrf\"\"\"fr double triple\"\"\"\nrf\"\"\"rf single triple\"\"\"\nrf\"\"\"rf double triple\"\"\"\nb\"\"\"b single triple\"\"\"\nb\"\"\"b double triple\"\"\"\nrb\"\"\"rb single triple\"\"\"\nrb\"\"\"rb double triple\"\"\"\nrb\"\"\"br single triple\"\"\"\nrb\"\"\"br double triple\"\"\"\n\n'single1single2'\n'single1double2'\n'double1single2'\n'double1double2'\n\n\ndef docstring_single_triple():\n    \"\"\"single triple\"\"\"\n\n\ndef docstring_double_triple():\n    \"\"\"double triple\"\"\"\n\n\ndef docstring_double():\n    \"double triple\"\n\n\ndef docstring_single():\n    \"single\"\n";

/** Output 2 of crates/ruff_python_formatter/tests/snapshots/format@quote_style.py.snap at 0.15.20 (quote-style = Double, line-width 88, indent-width 4, indent-style space) */
export const QUOTE_STYLE_DOUBLE_OUTPUT = "\"single\"  # this string is treated as a docstring\n\n\"double\"\nr\"r single\"\nr\"r double\"\nf\"f single\"\nf\"f double\"\nrf\"fr single\"\nrf\"fr double\"\nrf\"rf single\"\nrf\"rf double\"\nb\"b single\"\nb\"b double\"\nrb\"rb single\"\nrb\"rb double\"\nrb\"br single\"\nrb\"br double\"\n\n\"\"\"single triple\"\"\"\n\"\"\"double triple\"\"\"\nr\"\"\"r single triple\"\"\"\nr\"\"\"r double triple\"\"\"\nf\"\"\"f single triple\"\"\"\nf\"\"\"f double triple\"\"\"\nrf\"\"\"fr single triple\"\"\"\nrf\"\"\"fr double triple\"\"\"\nrf\"\"\"rf single triple\"\"\"\nrf\"\"\"rf double triple\"\"\"\nb\"\"\"b single triple\"\"\"\nb\"\"\"b double triple\"\"\"\nrb\"\"\"rb single triple\"\"\"\nrb\"\"\"rb double triple\"\"\"\nrb\"\"\"br single triple\"\"\"\nrb\"\"\"br double triple\"\"\"\n\n\"single1single2\"\n\"single1double2\"\n\"double1single2\"\n\"double1double2\"\n\n\ndef docstring_single_triple():\n    \"\"\"single triple\"\"\"\n\n\ndef docstring_double_triple():\n    \"\"\"double triple\"\"\"\n\n\ndef docstring_double():\n    \"double triple\"\n\n\ndef docstring_single():\n    \"single\"\n";
