#!/usr/bin/env node
/**
 * Writes docs/LEDGER.md: what is done, what is next, and each one's tier.
 *
 * Generated from the catalog and from what is actually on disk, so it cannot
 * claim a tool is finished when the folder is empty. This is the file to read
 * when picking the work back up.
 */
import { writeFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT, CATEGORY_LABELS, loadCatalog } from './lib/catalog.mjs';

const catalog = loadCatalog();

const pagesDir = join(ROOT, 'apps', 'web', 'src', 'tools');
const pages = new Set(
  existsSync(pagesDir)
    ? readdirSync(pagesDir)
        .filter((f) => f.endsWith('.ts'))
        .map((f) => f.replace(/\.ts$/, ''))
    : [],
);

const toolsDir = join(ROOT, 'tools');
const packages = new Set(
  existsSync(toolsDir) ? readdirSync(toolsDir).filter((d) => statSync(join(toolsDir, d)).isDirectory()) : [],
);

const state = (c) => {
  const hasPackage = packages.has(c.id);
  const hasPage = pages.has(c.id);
  if (hasPackage && hasPage) return 'shipped';
  if (hasPackage && !hasPage) return 'logic done, no page';
  if (!hasPackage && hasPage) return 'page with no logic';
  return 'not started';
};

const withState = catalog.map((c) => ({ ...c, state: state(c) }));

const shipped = withState.filter((c) => c.state === 'shipped');
const partial = withState.filter((c) => c.state === 'logic done, no page' || c.state === 'page with no logic');
const remaining = withState.filter((c) => c.state === 'not started');

// Order the remaining work by build tier, then alphabetically by name.
const nextUp = [...remaining].sort((a, b) => a.tier - b.tier || a.name.localeCompare(b.name));

const md = [];
md.push('# Implementation ledger');
md.push('');
md.push(
  'Generated by `pnpm ledger` from the catalog and from what is actually on disk. Do not edit by hand. This is the file to read when picking the work back up.',
);
md.push('');
md.push('## Where things stand');
md.push('');
md.push('| | Count |');
md.push('| --- | --- |');
md.push(`| Catalog | ${catalog.length} |`);
md.push(`| **Shipped: logic, tests and a page** | **${shipped.length}** |`);
md.push(`| Half done | ${partial.length} |`);
md.push(`| Not started | ${remaining.length} |`);
md.push('');

if (partial.length > 0) {
  md.push('## Half done, finish these first');
  md.push('');
  md.push('| Tool | Id | State |');
  md.push('| --- | --- | --- |');
  for (const c of partial) md.push(`| ${c.name} | \`${c.id}\` | ${c.state} |`);
  md.push('');
}

md.push('## Shipped');
md.push('');
md.push('| Tool | Id | Category |');
md.push('| --- | --- | --- |');
for (const c of [...shipped].sort((a, b) => a.name.localeCompare(b.name))) {
  md.push(`| ${c.name} | \`${c.id}\` | ${CATEGORY_LABELS[c.category] ?? c.category} |`);
}
md.push('');

md.push('## Remaining, in suggested order');
md.push('');
md.push(
  'Ordered by build tier, then alphabetically by name. Tier 1 is pure logic with published test vectors; tier 2 needs a library or a browser API; tier 3 is interface-heavy or needs a large asset.',
);
md.push('');
md.push('| # | Tool | Id | Tier | Category | What it needs |');
md.push('| --- | --- | --- | --- | --- | --- |');
nextUp.forEach((c, i) => {
  const needs =
    c.tier === 1
      ? 'Logic and tests only'
      : c.tier === 2
        ? 'A reviewed dependency or a browser API'
        : 'Interactive interface work, or a large bundled asset';
  md.push(
    `| ${i + 1} | ${c.name} | \`${c.id}\` | ${c.tier} | ${CATEGORY_LABELS[c.category] ?? c.category} | ${needs} |`,
  );
});
md.push('');

md.push('## How to pick this up');
md.push('');
md.push('```sh');
md.push('pnpm install');
md.push('node scripts/new-tool.mjs <id>     # from the table above');
md.push('# write src/index.ts, src/meta.json and test/');
md.push('pnpm sync && pnpm verify');
md.push('# then add apps/web/src/tools/<id>.ts and run pnpm e2e');
md.push('```');
md.push('');
md.push(
  '`CONTRIBUTING.md` has the rules each tool has to satisfy. They are all enforced by `pnpm verify`, so nothing depends on remembering them.',
);
md.push('');

writeFileSync(join(ROOT, 'docs', 'LEDGER.md'), md.join('\n'));
console.log(`Ledger written: ${shipped.length} shipped, ${partial.length} half done, ${remaining.length} remaining.`);
