import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import {
  KEY_TYPES,
  KeyConverterError,
  RSA_GENERATE_BITS,
  generateRsa,
  keyFromGeneratedRsa,
  keyOutputs,
  meta as toolMeta,
} from '../src/index';
import { readSpki, writePkcs8, writeSpki } from '../src/formats';
import { sshPublicBlob, sshPublicLine } from '../src/openssh';
import { sshFingerprints } from '../src/fingerprint';
import { RSA2048_SPKI_DER_B64, RSA2048_SSH_LINE, RSA2048_SSH_MD5, RSA2048_SSH_SHA256 } from './fixtures/rsa2048-public';

/**
 * Second opinions: Node's Web Crypto and node:crypto (an OpenSSL-backed implementation that is not this package) for
 * keys and hashes; ssh-keygen 10.2p1 (recorded in test/fixtures) for the OpenSSH line and its fingerprints; RFC 4253
 * section 6.6 for the ssh-rsa encoding; RFC 8032 section 7.1 and RFC 8709 for the Ed25519 public key and its blob.
 */

const spies = {
  log: vi.spyOn(console, 'log'),
  warn: vi.spyOn(console, 'warn'),
  error: vi.spyOn(console, 'error'),
};
beforeEach(() => {
  for (const spy of Object.values(spies)) spy.mockImplementation(() => undefined);
});
afterEach(() => {
  for (const spy of Object.values(spies)) expect(spy).not.toHaveBeenCalled();
  for (const spy of Object.values(spies)) spy.mockReset();
});

const subtle = globalThis.crypto.subtle;

interface NodeRsaKey {
  pkcs8: Uint8Array;
  spki: Uint8Array;
  jwk: JsonWebKey;
}

/** An RSA key made by Node's own Web Crypto, with its exports, so the package is compared with what the engine wrote. */
async function nodeRsaKey(bits: number): Promise<NodeRsaKey> {
  const pair = (await subtle.generateKey(
    { name: 'RSASSA-PKCS1-v1_5', modulusLength: bits, publicExponent: Uint8Array.of(1, 0, 1), hash: 'SHA-256' },
    true,
    ['sign', 'verify'],
  )) as CryptoKeyPair;
  return {
    pkcs8: new Uint8Array(await subtle.exportKey('pkcs8', pair.privateKey)),
    spki: new Uint8Array(await subtle.exportKey('spki', pair.publicKey)),
    jwk: await subtle.exportKey('jwk', pair.privateKey),
  };
}

function fromBase64Url(text: string): Uint8Array {
  return new Uint8Array(Buffer.from(text, 'base64url'));
}

function sameBytes(left: Uint8Array, right: Uint8Array): boolean {
  return Buffer.from(left).equals(Buffer.from(right));
}

function hex(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString('hex');
}

/** Reads the length-prefixed strings of an SSH blob (RFC 4251 section 5) without any help from the package. */
function sshStrings(blob: Uint8Array): Uint8Array[] {
  const out: Uint8Array[] = [];
  const view = new DataView(blob.buffer, blob.byteOffset, blob.byteLength);
  let at = 0;
  while (at < blob.length) {
    const length = view.getUint32(at);
    out.push(blob.subarray(at + 4, at + 4 + length));
    at += 4 + length;
  }
  expect(at).toBe(blob.length);
  return out;
}

const text = (bytes: Uint8Array): string => Buffer.from(bytes).toString('latin1');

function thrown(call: () => unknown): unknown {
  try {
    call();
  } catch (err) {
    return err;
  }
  throw new Error('the call did not throw');
}

it('an RSA key generated by Web Crypto reads back from its PKCS8 and SPKI bytes and is written again byte for byte', async () => {
  // Several keys, because the PKCS8 length varies by a byte or two with the random primes (DER integer lengths).
  for (let n = 0; n < 8; n++) {
    const made = await nodeRsaKey(2048);
    const key = keyFromGeneratedRsa(made.pkcs8, made.spki);
    expect(key.type).toBe('rsa');
    expect(sameBytes(writePkcs8(key), made.pkcs8)).toBe(true);
    expect(sameBytes(writeSpki(key), made.spki)).toBe(true);
    // Every number of the model equals the same number in the engine's own JSON Web Key (RFC 7518 section 6.3).
    const jwk = made.jwk;
    for (const name of ['n', 'e', 'd', 'p', 'q', 'dp', 'dq', 'qi'] as const) {
      expect(hex(key[name]!), name).toBe(hex(fromBase64Url(jwk[name]!)));
    }
  }
  // The package's own generator gives bytes that read the same way.
  const own = await generateRsa(2048);
  const ownKey = keyFromGeneratedRsa(own.pkcs8, own.spki);
  expect(sameBytes(writePkcs8(ownKey), own.pkcs8)).toBe(true);
  expect(sameBytes(writeSpki(ownKey), own.spki)).toBe(true);
}, 60_000);

it('a public key that does not belong to the private key is refused with a plain message', async () => {
  const first = await nodeRsaKey(2048);
  const second = await nodeRsaKey(2048);
  const err = thrown(() => keyFromGeneratedRsa(first.pkcs8, second.spki));
  expect(err).toBeInstanceOf(KeyConverterError);
  const message = (err as KeyConverterError).message;
  expect(message).toMatch(/does not belong/i);
  // No part of either key is in the message.
  for (const piece of [first.jwk.n!, first.jwk.d!, second.jwk.n!].map((v) => v.slice(0, 12))) {
    expect(message).not.toContain(piece);
  }
}, 60_000);

it('RSA generation offers exactly 2048, 3072 and 4096 bits with exponent 65537 and nothing else', async () => {
  expect([...RSA_GENERATE_BITS]).toEqual([2048, 3072, 4096]);
  expect(KEY_TYPES.filter((t) => t.id.startsWith('rsa')).map((t) => t.id)).toEqual([
    'rsa-2048',
    'rsa-3072',
    'rsa-4096',
  ]);
  for (const bits of [2048, 3072, 4096] as const) {
    const made = await generateRsa(bits);
    const key = keyFromGeneratedRsa(made.pkcs8, made.spki);
    // The modulus has exactly the requested number of bits, and the public exponent is 65537 (0x010001).
    const top = key.n[0]!;
    expect(key.n.length * 8 - (Math.clz32(top) - 24)).toBe(bits);
    expect(hex(key.e)).toBe('010001');
  }
  // Nothing else is offered, however it is spelled.
  for (const bits of [0, 1024, 2047, 2049, 4097, 8192, 16384, -2048, 2048.5, Number.NaN, Number.POSITIVE_INFINITY]) {
    const outcome = await generateRsa(bits as 2048).then(
      () => 'made a key',
      (err: unknown) => err,
    );
    expect(outcome, String(bits)).toBeInstanceOf(KeyConverterError);
  }
  const notANumber = await generateRsa('2048' as unknown as 2048).then(
    () => 'made a key',
    (err: unknown) => err,
  );
  expect(notANumber).toBeInstanceOf(KeyConverterError);
}, 60_000);

it('the OpenSSH public line of an RSA key carries the RFC 4253 ssh-rsa encoding with exponent 65537', async () => {
  const made = await nodeRsaKey(2048);
  const key = keyFromGeneratedRsa(made.pkcs8, made.spki);
  const line = sshPublicLine(key, 'me@example');
  // The fixed beginning of every ssh-rsa key with exponent 65537: string "ssh-rsa", then mpint 0x010001.
  expect(line.startsWith('ssh-rsa AAAAB3NzaC1yc2EAAAADAQAB')).toBe(true);
  expect(line.endsWith(' me@example')).toBe(true);
  expect(sshPublicLine(key, '').includes(' ', 'ssh-rsa '.length)).toBe(false);
  const parts = line.split(' ');
  expect(parts[0]).toBe('ssh-rsa');
  const blob = new Uint8Array(Buffer.from(parts[1]!, 'base64'));
  expect(sameBytes(blob, sshPublicBlob(key))).toBe(true);
  // RFC 4253 section 6.6: string "ssh-rsa", mpint e, mpint n. An mpint carries a zero octet in front of a top bit.
  const [name, e, n] = sshStrings(blob);
  expect(text(name!)).toBe('ssh-rsa');
  expect(hex(e!)).toBe('010001');
  const modulus = fromBase64Url(made.jwk.n!);
  expect(n![0]).toBe(0);
  expect(hex(n!.subarray(1))).toBe(hex(modulus));

  // ssh-keygen 10.2p1 printed this line and these fingerprints for an RSA 2048 key made by OpenSSL 3.5.5.
  const published = readSpki(new Uint8Array(Buffer.from(RSA2048_SPKI_DER_B64, 'base64')));
  expect(published.type).toBe('rsa');
  expect(sshPublicLine(published, '')).toBe(RSA2048_SSH_LINE);
  const printed = sshFingerprints(sshPublicBlob(published));
  expect(printed.sha256).toBe(RSA2048_SSH_SHA256);
  expect(printed.md5).toBe(RSA2048_SSH_MD5);
}, 60_000);

it('SSH fingerprints of the RFC 8032 test public key are the SHA256 and MD5 values ssh-keygen prints', () => {
  // RFC 8032 section 7.1, TEST 1, the public key; RFC 8709 section 4: string "ssh-ed25519", string key.
  const publicKey = Uint8Array.from(
    Buffer.from('d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a', 'hex'),
  );
  const name = Buffer.from('ssh-ed25519', 'latin1');
  const blob = Buffer.concat([
    Buffer.from([0, 0, 0, name.length]),
    name,
    Buffer.from([0, 0, 0, publicKey.length]),
    Buffer.from(publicKey),
  ]);
  // Printed by `ssh-keygen -l -E sha256 -f` and `-E md5 -f` (OpenSSH 10.2p1) for the line built from this blob.
  const printed = sshFingerprints(new Uint8Array(blob));
  expect(printed.sha256).toBe('SHA256:bbXpuKG6zhzdmnxq256TlqzFBzRl2f6OOg722cYNbU8');
  expect(printed.md5).toBe('MD5:cf:07:be:9d:68:ae:65:54:6d:a0:93:c3:6f:bd:0d:82');
  expect(blob.toString('base64')).toBe('AAAAC3NzaC1lZDI1NTE5AAAAINdamAGCsQq31Uv+08lkBzoO4XLz2qYjJa8CGmj3B1Ea');

  // The forms: SHA256 is unpadded Base64 of the digest, MD5 is lower case hex with colons, whatever the blob is.
  for (const length of [0, 1, 2, 3, 31, 100]) {
    const input = Uint8Array.from({ length }, (_, i) => (i * 37 + 11) & 255);
    const fingerprints = sshFingerprints(input);
    const sha256 = createHash('sha256').update(input).digest('base64').replace(/=+$/, '');
    const md5 = createHash('md5').update(input).digest('hex').match(/../g)!.join(':');
    expect(fingerprints.sha256).toBe(`SHA256:${sha256}`);
    expect(fingerprints.md5).toBe(`MD5:${md5}`);
  }
});

it('the key outputs list the PKCS8 and SPKI blocks, the OpenSSH line and both fingerprints', async () => {
  const made = await nodeRsaKey(2048);
  const key = keyFromGeneratedRsa(made.pkcs8, made.spki);
  const result = keyOutputs(key, { comment: 'work laptop' });

  expect(result.blocks.map((b) => b.id)).toEqual(['pkcs8', 'spki', 'ssh-public']);
  expect(result.blocks.map((b) => b.private)).toEqual([true, false, false]);
  expect(result.blocks.map((b) => b.label)).toEqual([
    'Private key, PKCS#8 (PEM)',
    'Public key, SubjectPublicKeyInfo (PEM)',
    'OpenSSH public key',
  ]);

  // The armour is put together here from pieces, as the fixtures rule says, around Node's own export.
  const wrap = (body: string) => body.match(/.{1,64}/g)!.join('\n');
  const pem = (label: string, bytes: Uint8Array) =>
    '-----BEGIN ' + label + '-----\n' + wrap(Buffer.from(bytes).toString('base64')) + '\n-----END ' + label + '-----\n';
  expect(result.blocks[0]!.text).toBe(pem('PRIVATE KEY', made.pkcs8));
  expect(result.blocks[1]!.text).toBe(pem('PUBLIC KEY', made.spki));
  expect(result.blocks[2]!.text).toBe(sshPublicLine(key, 'work laptop'));

  // The fingerprints are those of the blob inside the line, computed by node:crypto.
  const blob = Buffer.from(result.blocks[2]!.text.split(' ')[1]!, 'base64');
  expect(result.fingerprints).toEqual([
    ['SHA256', 'SHA256:' + createHash('sha256').update(blob).digest('base64').replace(/=+$/, '')],
    ['MD5', 'MD5:' + createHash('md5').update(blob).digest('hex').match(/../g)!.join(':')],
  ]);
  expect(result.facts).toEqual([
    ['Key type', 'RSA'],
    ['Size in bits', '2048'],
    ['Public exponent', '65537'],
  ]);
  expect(result.warnings).toEqual([]);

  // The comment is optional, at most 256 characters, and holds no line break.
  expect(keyOutputs(key, { comment: '' }).blocks[2]!.text.includes(' ', 'ssh-rsa '.length)).toBe(false);
  expect(keyOutputs(key, { comment: 'x'.repeat(256) }).blocks[2]!.text.endsWith(' ' + 'x'.repeat(256))).toBe(true);
  for (const bad of ['x'.repeat(257), 'one\ntwo', 'one\rtwo']) {
    const err = thrown(() => keyOutputs(key, { comment: bad }));
    expect(err).toBeInstanceOf(KeyConverterError);
    expect((err as KeyConverterError).message).toMatch(/comment/i);
    expect((err as KeyConverterError).message).not.toContain('one');
  }
}, 60_000);

it('meta pins @noble/curves and @noble/hashes exactly', () => {
  expect(toolMeta.dependencies).toEqual({ '@noble/curves': '2.4.0', '@noble/hashes': '2.4.0' });
  const packageJson = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8')) as {
    dependencies: Record<string, string>;
  };
  expect(packageJson.dependencies).toEqual({ '@noble/curves': '2.4.0', '@noble/hashes': '2.4.0' });
  // The documentation fields a visitor reads are all filled in.
  expect(toolMeta.limits.length).toBeGreaterThanOrEqual(3);
  expect(toolMeta.limits.join(' ')).toMatch(/60 seconds/);
  expect(toolMeta.limits.join(' ')).toMatch(/getRandomValues/);
});
