"""Makes stdnum-corpus.ts: numbers generated by python-stdnum, the second opinion for the check digit schemes.

Run from a scratch virtual environment that holds python-stdnum 2.2 (never the machine's own Python):

    python -m venv venv-14
    venv-14/Scripts/python -m pip install python-stdnum==2.2
    venv-14/Scripts/python tools/luhn/test/fixtures/make-fixtures.py tools/luhn/test/fixtures/stdnum-corpus.ts
    pnpm exec prettier --write tools/luhn/test/fixtures/stdnum-corpus.ts

It writes 400 random valid numbers each of ISBN-10, ISBN-13, EAN-13, EAN-8, UPC-A and ISIN and one valid IBAN for each of
the 89 countries python-stdnum lists (a random basic account number of the country's registered shape), 2,489 in all, from
a fixed seed so a rerun gives the same file. Every number is also read back by python-stdnum's own validate before it is
written (an IBAN without the national account checks, which a random account part cannot satisfy), so the corpus holds only
numbers the library accepts. The tests never run Python; they read the committed file.
"""

import random
import re
import string
import sys
import os

import stdnum
from stdnum import ean, iban, isbn, isin

SEED = 14080
random.seed(SEED)
# The country codes python-stdnum accepts in an ISIN (ISO 3166 plus the special codes such as XS and EU).
ISIN_COUNTRIES = sorted(isin._country_codes)


def digits(n):
    return ''.join(random.choice('0123456789') for _ in range(n))


def alnum(n, kind):
    pool = {'n': '0123456789', 'a': string.ascii_uppercase, 'c': string.ascii_uppercase + string.digits}[kind]
    return ''.join(random.choice(pool) for _ in range(n))


out = {'isbn10': [], 'isbn13': [], 'ean13': [], 'ean8': [], 'upca': [], 'isin': [], 'iban': []}
for _ in range(400):
    body = digits(9)
    out['isbn10'].append(body + isbn._calc_isbn10_check_digit(body))
    body = random.choice(['978', '979']) + digits(9)
    out['isbn13'].append(body + ean.calc_check_digit(body))
    body = digits(12)
    out['ean13'].append(body + ean.calc_check_digit(body))
    body = digits(7)
    out['ean8'].append(body + ean.calc_check_digit(body))
    body = digits(11)
    out['upca'].append(body + ean.calc_check_digit(body))
    body = random.choice(ISIN_COUNTRIES) + alnum(9, 'c')
    out['isin'].append(body + isin.calc_check_digit(body))

# One IBAN per country in python-stdnum's iban.dat, with a random account part of the registered shape ("4!n4!n12!c").
lengths = {}
dat = os.path.join(os.path.dirname(stdnum.__file__), 'iban.dat')
with open(dat, encoding='utf-8') as handle:
    for line in handle:
        match = re.match(r'^([A-Z]{2})\s+country="([^"]*)"\s+bban="([^"]*)"', line)
        if not match:
            continue
        country, _name, shape = match.groups()
        account = ''.join(alnum(int(n), kind) for n, _bang, kind in re.findall(r'(\d+)(!?)([nac])', shape))
        check = iban.calc_check_digits(country + '00' + account)
        number = country + check + account
        out['iban'].append(number)
        lengths[country] = len(number)

# The library must accept every number it was just asked to make.
for kind, check in (
    ('isbn10', isbn.validate),
    ('isbn13', isbn.validate),
    ('ean13', ean.validate),
    ('ean8', ean.validate),
    ('upca', ean.validate),  # python-stdnum reads a 12 digit EAN as a UPC-A
    ('isin', isin.validate),
    # check_country=False: the national account number checks (a Belgian modulus, for example) cannot hold for a random
    # account part; the check digits, the country, the length and the registered shape of the account part still apply.
    ('iban', lambda number: iban.validate(number, check_country=False)),
):
    for number in out[kind]:
        check(number)

# The published vectors the tests use are also read by the library (VIN has no python-stdnum module; its vectors are the
# regulation's own). The IBAN check digits are computed by the library too.
VECTORS = [
    (isbn.validate, ['0-306-40615-2', '080442957X', '978-0-11-000222-4', '9780777777770', '978-951-23-8888-2', '979-10-90636-07-1', '978-0-306-40615-7']),
    (ean.validate, ['4006381333931', '73513537', '036000291452', '0036000291452']),
    (lambda number: iban.validate(number, check_country=False), ['GB82 WEST 1234 5698 7654 32', 'DE89 3704 0044 0532 0130 00', 'AE070331234567890123456']),
    (isin.validate, ['US0378331005', 'GB0002634946', 'AU0000XVGZA3']),
]
published = 0
for check, numbers in VECTORS:
    for number in numbers:
        check(number)
        published += 1
assert isbn.to_isbn13('0-306-40615-2') == '978-0-306-40615-7'
assert iban.calc_check_digits('GB00WEST12345698765432') == '82'
assert iban.calc_check_digits('AE000331234567890123456') == '07'
assert isin.calc_check_digit('US037833100') == '5'

assert {k: len(v) for k, v in out.items()} == {
    'isbn10': 400, 'isbn13': 400, 'ean13': 400, 'ean8': 400, 'upca': 400, 'isin': 400, 'iban': 89
}, 'unexpected counts'

target = sys.argv[1]
with open(target, 'w', encoding='utf-8', newline='\n') as f:
    f.write('// Written by make-fixtures.py (python-stdnum %s, Python %s, random seed %d); see README.md.\n' % (stdnum.__version__, sys.version.split()[0], SEED))
    f.write('// Every number was accepted by python-stdnum validate before it was written. They are test data, not real identifiers.\n')
    for kind, name in (('isbn10', 'ISBN10'), ('isbn13', 'ISBN13'), ('ean13', 'EAN13'), ('ean8', 'EAN8'), ('upca', 'UPCA'), ('isin', 'ISIN')):
        f.write("export const STDNUM_%s: string[] = '%s'.split(' ');\n" % (name, ' '.join(out[kind])))
    f.write("export const STDNUM_IBAN: string[] = '%s'.split(' ');\n" % ' '.join(out['iban']))
    f.write('// The total length python-stdnum holds for each country, for comparison with the registry release.\n')
    f.write('export const STDNUM_IBAN_LENGTHS: Record<string, number> = %s;\n' % ('{' + ', '.join("%s: %d" % (c, n) for c, n in sorted(lengths.items())) + '}'))
print({k: len(v) for k, v in out.items()}, 'countries', len(lengths), 'published vectors accepted', published)
