/**
 * Published clang-format fixtures, vendored verbatim.
 *
 * Repository: https://github.com/llvm/llvm-project
 * Tag:        llvmorg-23.1.1
 * Path:       clang/docs/ClangFormatStyleOptions.rst (section IndentWidth) -- more files are added further down
 * URL:        https://github.com/llvm/llvm-project/blob/llvmorg-23.1.1/clang/docs/ClangFormatStyleOptions.rst
 * Licence:    Apache-2.0 WITH LLVM-exception (see ./LICENSE, clang/LICENSE.TXT at the same tag, unmodified)
 * Fetched:    2026-10-01 with curl from raw.githubusercontent.com
 *
 * Each constant is generated by a throwaway script with JSON.stringify, never typed by hand, so every space
 * survives. Do not edit.
 */

/** The code of the IndentWidth example before formatting: the documented block on one line (the documentation shows only the formatted result) */
export const INDENT_WIDTH_DOC_INPUT = "void f() { someFunction(); if (true, false) { f(); } }\n";

/** The formatted block of the IndentWidth example, "IndentWidth: 3", exactly as the documentation prints it, plus the final line break the formatter ends with */
export const INDENT_WIDTH_DOC_OUTPUT = "void f() {\n   someFunction();\n   if (true, false) {\n      f();\n   }\n}\n";
